### ISSUE TITLE
Player Data refresh request is funky right now

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/vainsocial#18]
We need the following flow:

1. user comes to the site and searches for a player by IGN. We check the lastMatchPullDate and use that to setup the endDate
   (assume that processor has checked the logic between last pull date and most recent match date on participant and set the lastMatch date accordingly) @schneefux - confirm
2. The job also needs to check that previous job should not have been in last x hours (this should be read from a configuration)
3. If the player profile/data exists in DB, send back the data and show the player match data
4. If the player data is not in DB, send back to leaderboard with a message that we are awaiting a refresh
5. On the leaderboards we need to show an update when the job is done - either it got the data or it didn't.
6. we may want to put leaderboards on home page itself and only reload the page if there is data
7. if there is no data we have to let the user know clearly what may have happened (we need to make sure that it's not a system problem).
8. Also find a way to avoid the user from spamming the search

**Comment by schneefux** [comment]
Confirming 1, "should work".

Job "cooldowns" is a good idea and goes hand in hand with "spamming the search". Maybe we don't need to have an hour-long cooldown, because I'd assume that a player plays matches and opens our app to check on the matches they just played, so the maximum cooldown should be around ½h, which is the length of a match — what do you think?

The API should return data with only a delay of few minutes.

**Comment by kvahuja** [comment]
i don't want to return a player back. so maybe someone played and snowballed in 15 minutes. they want to brag about it and we will be late.  but 30 minute seems okay. any lesser and we significantly reduce our capacity to serve. 

spamming i meant one person just searching one after another different names. this will not classify on cooldown. we will have to see and if this happens might have to put in a IP filter on cooldown. but i don't think we need that at launch
