### ISSUE TITLE
If a player comes to home page from any page that has scheduled the job - we need to initiate the flow...

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/vainsocial#31]

**Comment by kvahuja** [comment]
done, although he won't know and will be taken to home page. not sure if we need to handle this. will wait for user feedback closing for now.

**Comment by schneefux** [comment]
It confused me at least, that I got redirected to home. I would have expected the page to load.
Maybe you can redirect to home and show the "waiting for API" window?

**Comment by kvahuja** [comment]
So here is what i think:
 - If a user got a URL, then they most certainly have visited us one and then it should always be shown. Unless a more savvy user like you and me modify the URL no one should encounter this. 
 - also, like any application if a page is unavailable or so, you get redirected. 

i dont want to add code for use cases i dont want to promote hence i dropped it. I will track the 302s in analytics and maybe will add it.

**Comment by schneefux** [comment]
What happens in the following scenario:
  * Spider is enabled
  * In low priority queue: 5000 players
  * Player searches himself
  * He is updated immediately as high priority
  * The player views his recent match, clicks on one of his ex teammates
  * The teammates' profile opens
  * ...and now? processor should have inserted one player record, but the webend should request a job nonetheless.

I think that is implemented, is it? Then everything is fine 😃

I think that being able to point at our "internal" URLs would be a benefit, for example if a bot decided to link to us, or say the Vainglory forums link player profiles.

**Comment by kvahuja** [comment]
So, the following is implemented. 

```
processor should have inserted one player record, but the webend should request a job nonetheless
```

Code from playercontroller. i have server code to sent a JSON object with job id as well so that UI can handle the case if a redirect happen.

what i dont have yet is "notifiy a player that his/her data has changed".  this is a use case independent of this yet there is overlap. so think if i am on my page or any page where i have a player, and suddenly we fire a refresh because of spider or anything else. we want to tell user we have new data. once i get that one, this use case will be complete. aka
 - i come, view myself, then click my friend
 - i see some records of my friend because we have partial pull. 
 - there will be a notification, we are checking (on top right)
 - if there is new data, please refresh sort of thing.
 - this popup will only come up if a job has been requested. which means the use case of - me searching -> opening the profile page -> doesnt fire a refresh will not have this popup.

of course issue is - web pulls or server pushes. we are using HTTP2 so technically i can use server push, but this is going to be tricky.



so a user hits our internal URL it will all work as long as data is in DB. if it's not there will be redirects and actions in background to make sure we dont ignore it.


```
public function show(String $region, String $name)
    {   
        $player = Player::where('name', $name)->get()->first();
        $now = new \DateTime(date(\DateTime::ISO8601));
        if (is_null($player)) {
            $createdAtEnd = new \DateTime(date(\DateTime::ISO8601));
        } else {
            $createdAtEnd = new \DateTime($player->last_match_created_date);
        }
        $jobId = $this->setupJob($player, $name, $region, $now, $createdAtEnd);
        if (!is_null($player)) {
            sleep(1);
            return view('common.player')->with('player', $player);
        } else {
            // didnt find the player in DB, search is already initiatied so just return back to home.
            $returnValue = array('code' => '404', 'jobId' => $jobId);
            return redirect('/')->with(json_encode($returnValue));
        }
    }
```

**Comment by kvahuja** [comment]
and on 

> I think that being able to point at our "internal" URLs would be a benefit, for example if a bot decided to link to us, or say the Vainglory forums link player profiles

i will eventually write a service to generate a detailed robots.txt for all player profiles to allow for Google to crawl and index. this way we will have all players searchable in google itself.

**Comment by schneefux** [comment]
👍
