### ISSUE TITLE
Check for running job before inserting

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vainsocial#46]
situation:
  * open `/players/eu/yamoma`
  * refresh
  * refresh
  * refresh

4 jobs are added and interfere. Check whether a job with `filter[playerNames]=player` has `status=running` or `status=open`.
Maybe this fixes some issues later in the chain.

**Comment by kvahuja** [comment]
ahhh this is the rate limiting i was talking about earlier which we need. cool, i will put something in.

**Comment by kvahuja** [comment]
@schneefux - review this. this is critical
