### ISSUE TITLE
Player update notifications

### ISSUE THREAD

**Issue by kvahuja** [vainglorygame/vainsocial#50]
from #31 

"notifiy a player that his/her data has changed". this is a use case independent of this yet there is overlap. so think if i am on my page or any page where i have a player, and suddenly we fire a refresh because of spider or anything else. we want to tell user we have new data. once i get that one, this use case will be complete. aka

i come, view myself, then click my friend
i see some records of my friend because we have partial pull.
there will be a notification, we are checking (on top right)
if there is new data, please refresh sort of thing.
this popup will only come up if a job has been requested. which means the use case of - me searching -> opening the profile page -> doesnt fire a refresh will not have this popup.
of course issue is - web pulls or server pushes. we are using HTTP2 so technically i can use server push, but this is going to be tricky.

so a user hits our internal URL it will all work as long as data is in DB. if it's not there will be redirects and actions in background to make sure we dont ignore it.

**Comment by kvahuja** [comment]
we need this. however this is going to be a major upgrade to support scale. not gonna happen in 1.0

>Laravel's event broadcasting allows you to broadcast your server-side Laravel events to your client-side JavaScript application using a driver-based approach to WebSockets. Currently, Laravel ships with Pusher and Redis drivers. The events may be easily consumed on the client-side using the Laravel Echo Javascript package.

**Comment by schneefux** [comment]
Return "needs update", then use AJAX until all data is available.
The backend is done when all 'grab' jobs with params.filter[playerNames]=player and all 'process' jobs with playername=player are 'finished'.
I will add dependency information to jobs so that you can check whether all child jobs of the grab job you opened are done.

**Comment by kvahuja** [comment]
i will add for dependency info to be available in Jobs. i want to write 1 query aka 

select status from jobs where master_job_id = $1 and if all those are finished i will assume done.

**Comment by kvahuja** [comment]
moved to meta
