### ISSUE TITLE
Make the region buttons be search submit buttons

### ISSUE THREAD

**Issue by schneefux** [vainglorygame/vainsocial#71]
Currently, a user
  * inserts their IGN
  * (presses enter and is confused)
  * selects the region
  * (is confused)
  * presses the search icon
  * is delayed or forwarded

I suggest changing the flow so that a user
  * inserts their IGN
  * presses a region button
  * is delayed or forwarded

which means removing the search icon and making the region buttons be more prominent.

**Comment by kvahuja** [comment]
moved to meta
